CorinaTAE/src/java/proiect/entities/Eveniment.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proiect.entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author CORI
 */
@Entity
@Table(name = "EVENIMENT")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Eveniment.findAll", query = "SELECT e FROM Eveniment e")
    , @NamedQuery(name = "Eveniment.findById", query = "SELECT e FROM Eveniment e WHERE e.id = :id")
    , @NamedQuery(name = "Eveniment.findByNume", query = "SELECT e FROM Eveniment e WHERE e.nume = :nume")
    , @NamedQuery(name = "Eveniment.findByDescriere", query = "SELECT e FROM Eveniment e WHERE e.descriere = :descriere")
    , @NamedQuery(name = "Eveniment.findByNrParticipanti", query = "SELECT e FROM Eveniment e WHERE e.nrParticipanti = :nrParticipanti")})
public class Eveniment implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    @NotNull
    @Column(name = "ID")
    private Long id;
    @Size(max = 250)
    @Column(name = "NUME")
    private String nume;
    @Size(max = 2000)
    @Column(name = "DESCRIERE")
    private String descriere;
    @Column(name = "NR_PARTICIPANTI")
    private Long nrParticipanti;

    public Eveniment() {
    }

    public Eveniment(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNume() {
        return nume;
    }

    public void setNume(String nume) {
        this.nume = nume;
    }

    public String getDescriere() {
        return descriere;
    }

    public void setDescriere(String descriere) {
        this.descriere = descriere;
    }

    public Long getNrParticipanti() {
        return nrParticipanti;
    }

    public void setNrParticipanti(Long nrParticipanti) {
        this.nrParticipanti = nrParticipanti;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Eveniment)) {
            return false;
        }
        Eveniment other = (Eveniment) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "proiect.entities.Eveniment[ id=" + id + " ]";
    }
    
}

CorinaTAE/src/java/jsf/EvenimentController.java
 package jsf;

import proiect.entities.Eveniment;
import jsf.util.JsfUtil;
import jsf.util.PaginationHelper;
import jpa.session.EvenimentFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("evenimentController")
@SessionScoped
public class EvenimentController implements Serializable {

    private Eveniment current;
    private DataModel items = null;
    @EJB
    private jpa.session.EvenimentFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public EvenimentController() {
    }

    public Eveniment getSelected() {
        if (current == null) {
            current = new Eveniment();
            selectedItemIndex = -1;
        }
        return current;
    }

    private EvenimentFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Eveniment) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Eveniment();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("EvenimentCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Eveniment) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("EvenimentUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Eveniment) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("EvenimentDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Eveniment getEveniment(java.lang.Long id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Eveniment.class)
    public static class EvenimentControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            EvenimentController controller = (EvenimentController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "evenimentController");
            return controller.getEveniment(getKey(value));
        }

        java.lang.Long getKey(String value) {
            java.lang.Long key;
            key = Long.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Long value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Eveniment) {
                Eveniment o = (Eveniment) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Eveniment.class.getName());
            }
        }

    }

}

CorinaTAE/web/eveniment/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateEvenimentTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateEvenimentLabel_id}" for="id" />
                    <h:inputText id="id" value="#{evenimentController.selected.id}" title="#{bundle.CreateEvenimentTitle_id}" required="true" requiredMessage="#{bundle.CreateEvenimentRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle.CreateEvenimentLabel_nume}" for="nume" />
                    <h:inputText id="nume" value="#{evenimentController.selected.nume}" title="#{bundle.CreateEvenimentTitle_nume}" />
                    <h:outputLabel value="#{bundle.CreateEvenimentLabel_descriere}" for="descriere" />
                    <h:inputText id="descriere" value="#{evenimentController.selected.descriere}" title="#{bundle.CreateEvenimentTitle_descriere}" />
                    <h:outputLabel value="#{bundle.CreateEvenimentLabel_nrParticipanti}" for="nrParticipanti" />
                    <h:inputText id="nrParticipanti" value="#{evenimentController.selected.nrParticipanti}" title="#{bundle.CreateEvenimentTitle_nrParticipanti}" />
                </h:panelGrid>
                <br />
                <h:commandLink action="#{evenimentController.create}" value="#{bundle.CreateEvenimentSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{evenimentController.prepareList}" value="#{bundle.CreateEvenimentShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateEvenimentIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

CorinaTAE/web/eveniment/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditEvenimentTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditEvenimentLabel_id}" for="id" />
                    <h:inputText id="id" value="#{evenimentController.selected.id}" title="#{bundle.EditEvenimentTitle_id}" required="true" requiredMessage="#{bundle.EditEvenimentRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle.EditEvenimentLabel_nume}" for="nume" />
                    <h:inputText id="nume" value="#{evenimentController.selected.nume}" title="#{bundle.EditEvenimentTitle_nume}" />
                    <h:outputLabel value="#{bundle.EditEvenimentLabel_descriere}" for="descriere" />
                    <h:inputText id="descriere" value="#{evenimentController.selected.descriere}" title="#{bundle.EditEvenimentTitle_descriere}" />
                    <h:outputLabel value="#{bundle.EditEvenimentLabel_nrParticipanti}" for="nrParticipanti" />
                    <h:inputText id="nrParticipanti" value="#{evenimentController.selected.nrParticipanti}" title="#{bundle.EditEvenimentTitle_nrParticipanti}" />
                </h:panelGrid>
                <h:commandLink action="#{evenimentController.update}" value="#{bundle.EditEvenimentSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditEvenimentViewLink}"/>
                <br />
                <h:commandLink action="#{evenimentController.prepareList}" value="#{bundle.EditEvenimentShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditEvenimentIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

CorinaTAE/web/eveniment/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListEvenimentTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListEvenimentEmpty}" rendered="#{evenimentController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{evenimentController.items.rowCount > 0}">
                    <h:outputText value="#{evenimentController.pagination.pageFirstItem + 1}..#{evenimentController.pagination.pageLastItem + 1}/#{evenimentController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{evenimentController.previous}" value="#{bundle.Previous} #{evenimentController.pagination.pageSize}" rendered="#{evenimentController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{evenimentController.next}" value="#{bundle.Next} #{evenimentController.pagination.pageSize}" rendered="#{evenimentController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{evenimentController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListEvenimentTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListEvenimentTitle_nume}"/>
                            </f:facet>
                            <h:outputText value="#{item.nume}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListEvenimentTitle_descriere}"/>
                            </f:facet>
                            <h:outputText value="#{item.descriere}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListEvenimentTitle_nrParticipanti}"/>
                            </f:facet>
                            <h:outputText value="#{item.nrParticipanti}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{evenimentController.prepareView}" value="#{bundle.ListEvenimentViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{evenimentController.prepareEdit}" value="#{bundle.ListEvenimentEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{evenimentController.destroy}" value="#{bundle.ListEvenimentDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{evenimentController.prepareCreate}" value="#{bundle.ListEvenimentCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListEvenimentIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

CorinaTAE/web/eveniment/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewEvenimentTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewEvenimentLabel_id}"/>
                    <h:outputText value="#{evenimentController.selected.id}" title="#{bundle.ViewEvenimentTitle_id}"/>
                    <h:outputText value="#{bundle.ViewEvenimentLabel_nume}"/>
                    <h:outputText value="#{evenimentController.selected.nume}" title="#{bundle.ViewEvenimentTitle_nume}"/>
                    <h:outputText value="#{bundle.ViewEvenimentLabel_descriere}"/>
                    <h:outputText value="#{evenimentController.selected.descriere}" title="#{bundle.ViewEvenimentTitle_descriere}"/>
                    <h:outputText value="#{bundle.ViewEvenimentLabel_nrParticipanti}"/>
                    <h:outputText value="#{evenimentController.selected.nrParticipanti}" title="#{bundle.ViewEvenimentTitle_nrParticipanti}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{evenimentController.destroyAndView}" value="#{bundle.ViewEvenimentDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewEvenimentEditLink}"/>
                <br />
                <h:commandLink action="#{evenimentController.prepareCreate}" value="#{bundle.ViewEvenimentCreateLink}" />
                <br />
                <h:commandLink action="#{evenimentController.prepareList}" value="#{bundle.ViewEvenimentShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewEvenimentIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>